### ISSUE TITLE
Wrong bug is targetted if links to multiple bugs are present in the same thread

### ISSUE THREAD

**Issue by nayanshah** [Microsoft/mail2bug#28]
Repro:
- Create bug using mail2bug
- Reply to thread with link to another bug, 
    e.g. Bug [1234](http://account.visualstudio.com): Other bug
- Use mnemonics / overrides to update the newly logged bug
- The "other bug" gets updated by the overrides.

**Comment by hershi** [comment]
Basically, what you're describing appears to be a case where M2B detected the thread as an "Append Only" thread. This is done based on one of two regular expressions - one for evaluating the subject of the email, and the other for evaluating the body of the email - which are provided in the following config nodes:
        <AppendOnlyEmailTitleRegex>.*(bug|work item)\s*#*\s*(?&lt;id&gt;\d+)</AppendOnlyEmailTitleRegex>
        <AppendOnlyEmailBodyRegex>!!!(bug|work item)\s*#*\s*(?&lt;id&gt;\d+)</AppendOnlyEmailBodyRegex>

Depending on how you configured those fields, what you're describing may be (and I think is most likely to be) by design. E.g. if you change the AppendOnlyEmailBodyRegex field by removing the 3 bangs (!!!), then any mention of "bug 1234" in the body would be detected and appended to. If you want to avoid this detection, you need to change the regex accordingly.
