### ISSUE TITLE
Submitting Bugs vs Report out of Bugs

### ISSUE THREAD

**Issue by dgtlrift** [Microsoft/mail2bug#33]
This is not really an issue so much as a clarification of capabilities.

Do tickets submitted to via email require that the user have a valid account on our exchange or can anyone who uses the email address associated with Mail2Bug submit/update a ticket?

Is there an ability to have approved list on external emails that can update tickets?

It appears that Mail2Bug is the user that actually updates tickets, but does it record in the TFS history the user that sent the mail that triggered the item creation or update?

Can Mail2Bug be used to assign issues to users beyond the visibility of our TFS?  IE - our TFS install is coupled to our Domain/Exchange system, but we have a partner company outside that develops products for us that does not have network access to our TFS instance, can Mail2Bug be used to forward the content of issues created?  How would we configure it to do so?

Also - regarding this issue - is there a list serve for this project to have such discussions that are not really issues?

Thanks much,
DG

**Comment by hershi** [comment]
* Mail2Bug has no functionality to limit processing only to emails from specific users
* It can record who sent the email - either by changing the "Changed By" field after (trying to) resolve the sender to a valid TFS/VSO username (see more details in the fully annotated config). Alternatively, you can use the "MessageBodyWithSender" special value that will include the sender's email address in the comment
* Assigning beyond the scope of your TFS/VSO is not really supported, since that needs to be supported by TFS/VSO to work (the tool doesn't fundamentally change how TFS/VSO behaves - it uses public interfaces)
