### ISSUE TITLE
Unexpected situation with 2 Mail2Bug aliases added at different times

### ISSUE THREAD

**Issue by derekleMSFT** [Microsoft/mail2bug#35]
When a different Mail2Bug e-mail alias is added to a thread that already had another Mail2Bug alias, could it do one of two things:
1) Update the existing bug with the settings of the new Mail2Bug alias
2) Open a new bug

We hit a situation where there was a long thread with Mail2Bug alias #1 that was added, created a bug, and then someone removed a bunch of addresses at some point, then I added Mail2Bug alias #2, and noticed it didn't actually create a new bug, or send me any notification. It did actually update the original bug (although because the original bug was closed, that accomplished nothing).

**Comment by hershi** [comment]
This is dependent on the specifics of your setup.
I am guessing that in your case the query for both M2B aliases had the original bug retrieved. If that is indeed the case, then whichever alias picks it up, it has no way to realize that the bug was actually created by a different instance and ignore it. You can create this kind of setup by introducing a differentiation in the bugs created by each of the instances (e.g. by setting some field to a different value in each instance) and then build separate queries for the two instances, such that they don't pick up each-other's bugs.

If the above is not the case, please provide some more details regarding the setup of the two instances, and ideally the relevant log excerpts for processing both emails, and I can try and look into it.
