### ISSUE TITLE
Suggestion: Support deployment as an Azure Web/Worker Role (or WebApp) with Web based config interface

### ISSUE THREAD

**Issue by acds** [Microsoft/mail2bug#37]
It seems deploying this to a VM means one is dependent on the VM to be running for the processing to work as expected. It would be great should anyone when to evolve this useful utility to have the boilerplate code in place to allow it to be easily deployed into he Azure environment ?

This can then utilize some of the High Availability PaaS components to ensure it always running.

An HTML/Web based config screen would also be a nice feature, leveraging Azure AD or similar for admin credentials.

**Comment by jeffwilcox** [comment]
I've hacked together a solution that lets me use _mail2bug_ using Azure App Service WebJobs.

I still for now use an XML configuration file for all the rules and goo, but then use Azure KeyVault to actually store and retrieve the secrets (account passwords) when the job runs.

It's early from my end, but I would be happy to eventually prep a PR or at least share what I've done, since it is more resilient and easy to configure than a VM.

**Comment by acds** [comment]
Hi Jeff, I'd be more than happy to try it out! My other burning issue is being able to use a shared mailbox, as that does not seem to work. 

From a configuration perspective at least moving it to the app.config might make it more consistent ?

**Comment by jeffwilcox** [comment]
@acds FYI the App Service + WebJob is enabled by the Azure KeyVault support I'm starting a PR loop on here: https://github.com/Microsoft/mail2bug/pull/39

**Comment by acds** [comment]
hi @jeffwilcox just checking in to see if you have got anywhere with he PR? I see that @hershi is looking at it to "merge it in"....

It would be good to get https://github.com/Microsoft/mail2bug/issues/31 fixed too...

**Comment by jeffwilcox** [comment]
We've been running great with it deployed as an Azure App Service web job since July. Let me know if you need a pointer to what that looks like, maybe I can get a short blog post out on that.

**Comment by acds** [comment]
Hi @jeffwilcox it would be good to have a short blog pos as you indicate...

Thanks!

**Comment by jeffwilcox** [comment]
Finally blogged about this... https://www.jeff.wilcox.name/2017/02/mail2bug/

**Comment by acds** [comment]
Thanks!

On Feb 24, 2017, at 9:48 AM, Jeff Wilcox <notifications@github.com<mailto:notifications@github.com>> wrote:


Finally blogged about this... https://www.jeff.wilcox.name/2017/02/mail2bug/

**Comment by hershi** [comment]
Totally my bad for letting this PR wait for practically forever. Will try to take it in by end of this weekend
Thanks for giving me the nudge I need

**Comment by hershi** [comment]
The change is now merged.
I'll add the link to the blog post on the main documentation page for reference.
@jeffwilcox, I have one ask - since I don't have any setup that's using this as an Azure service, the only testing I've done for the merged version is that the existing functionality still works for all the instances I have. Can you try it out with your setup to make sure the merge went through correctly (I had to make some changes to resolve conflicts) and Azure support works as expected

Thanks for implementing this Jeff!

**Comment by acds** [comment]
@jeffwilcox Just getting back to this...which fork do I use to leverage the WebRole functionality ? 

I Read your blog article, and per the Microsoft one I don see the configuration folder or the following files:
.deployment 
deploy.cmd or
settings.job

Thanks

**Comment by jeffwilcox** [comment]
The capability as I implemented it is for Azure App Service (web sites), _not_ web role.

**Comment by acds** [comment]
@jeffwilcox yes sorry get that, but don't see the structure per you blog post...no configuration folder ?

Its a shame one needs to be a Standard or Premium Azure Web App Tier to have reliable WebJob scheduling with "Always On" functionality. On this basis is it easy to combine in with another Code base that actually runs a website so mailtobug can just be a WebJob within that website?

**Comment by jeffwilcox** [comment]
@acds the configuration folder is your standard set of mail2bug configuration files, those are for you to create and define.

As to pricing, I've always found App Service to be rather affordable, since your App Service Plan is what you pay for, not individual sites within the plan. As a result, the incremental cost of using mail2bug if you're already using App Service is no cost ($0).
