### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mgolban** [Microsoft/mail2bug#55]
Hello all,

I have configure my company TFS project for Bug2mail service.
The email account used is my company email, but, when the service starts I get error message : Could not establish trust relationship for the SSL/TLS secure channel. ---> 
I have modified on purpose in the logfile for: Marius.Golban@company.com, domain\3mgolban, ************
I will attached the entire logfile, maybe someone has an idea.

Thanks 
Marius Golban

[Error_Bug2Mail.txt](https://github.com/Microsoft/mail2bug/files/750480/Error_Bug2Mail.txt)

**Comment by hershi** [comment]
It appears that Exchange is not happy about your certificate or method of authentication. This is probably due to the way Exchange is configured and what it requires for successful login via the EWS API.

Unfortunately, I'm not enough of an expert on Exchange/EWS to help much with this. I'd suggest following up with the admin of your Exchange server, or possibly in MSDN or possibly StackOverflow questions related to Exchange.
