### ISSUE TITLE
Suggest remove SimpleWebTokenCredential

### ISSUE THREAD

**Issue by gxclarke** [Microsoft/mail2bug#58]
`TFSWorkItemManager.GetServiceIdentityCredentials` adds both `SimpleWebTokenCredential` and `WindowsCredential` (containing `NetworkCredential`) to the list of credentials to try for authentication.

The second one correctly authenticates the service identity. However, the first one seems to ignore the provided credentials and uses the cookie of the logged in windows user or prompts for login if not available.

This isn't desired behavior, In my case, I had inadvertently logged in to VSO as a different user when I was prompted for windows credentials the first time, and thereafter couldn't figure out why bugs were being created from the wrong user account.

To fix, I have removed the `SimpleWebTokenCredential` from `GetServiceIdentityCredentials`. If my assessment is correct, please let me know if you prefer to have this fixed via a pull request.

**Comment by hershi** [comment]
That makes sense @gxclarke . It's mostly a remnant from an interim phase when introducing VSO support, but I didn't bother to remove it because I wasn't sure who might be using it.
Since the scenario you describe can definitely cause confusion and issues, I'm fine with removing it (it can always be recovered if we find it's really needed by someone). I'll try to get to it in the next few days, though PR would also be good if you get to it before me

Thanks!
