### ISSUE TITLE
Monitor more email addresses

### ISSUE THREAD

**Issue by liching001** [Microsoft/mail2bug#62]
Would like to find out, can i setup multiple email addresses to be monitor in the organizations? Is it set at different instances in the config file? If yes, how to cater for the password.bin files?

**Comment by jeffwilcox** [comment]
We monitor multiple addresses with multiple configuration files, you can use the `AltPasswordFile` option I believe. Check out the annotated reference here: https://github.com/Microsoft/mail2bug/blob/master/Documentation/FullyAnnotatedConfigReference.xml

**Comment by hershi** [comment]
You can put multiple instances into one configuration file, or use multiple files, or a mix of both (i.e. you can have multiple files, each with one or more instances).
You can reuse the same username/password files for all of them, and this would even speed up startup time (since authentication against EWS will be done only once per username/password pair).
