### ISSUE TITLE
Keyword activation? 

### ISSUE THREAD

**Issue by alexdresko** [Microsoft/mail2bug#7]
Can this tool be configured to only process emails with specific keywords in them? Maybe also a keyword to help the tool determine what kind of work item to create... and a keyword to help the tool figure out which team project to create the work item in? 

:)

**Comment by hershi** [comment]
That's a great idea for a new feature - using keywords in different fields to route to the right instance I'll look into the best way to implement that.

There _is_ a way to approximate that today with the tool, by leveraging the EWSByFolder service type and combining it with Exchange routing. The basic idea is this:
  * You create a folder under the mailbox root (i.e. not under Inbox, but directly under the root), one for each config instance you need - where the config instance defines the project, work-item type, etc. as it does in the standard version
  * You create **server-side** exchange rules that route messages to these folders based on keywords (or any other criteria you're interested in)
  * You create a config instance per each configuration you need, and use the following settings:
    * \Config\Instances\InstanceConfig\EmailSettings\ServiceType - set it to EWSByFolder
    * \Config\Instances\InstanceConfig\EmailSettings\IncomingFolder - set it to the name of the folder you created above for this instance
  * The rest of the settings are the same

The biggest downside of this approach is its reliance on Exchange rules - that's just another possible point-of-failure, and also it breaks the configuration up such that not everything is there in the config file. I'm going to look into adding the support directly in the tool so that this can be better supported in the long run.

That being said, I hope the above unblocks you for now

**Comment by alexdresko** [comment]
I'm not particularly stuck at the moment, so I've got time to hash this out. I asked the original question before even really looking deep enough into how to get this thing configured. I'm definitely interested in getting this set up though. The current work-around doesn't seem too bad. As I understand it, Exchange is already a requirement, so Exchange rules are there anyway. I do have access to Exchange or Office 365 for all of the various projects I work on, fortunately...  As far as my situation is concerned, the biggest point of failure is that I don't really have a server for one of the projects I work on. I'd have to either use my laptop or "borrow" one of the servers from another client's project.

**Comment by acds** [comment]
Being able to deploy to an Azure Web App/Web Role/Worker Role would be neat...per #37

**Comment by hershi** [comment]
@acds that one is now merged

**Comment by hershi** [comment]
@alexdresko As per what @acds was referring to - there is now support for running it as an Azure service - required code is merged, and there's a blog post from @jeffwilcox explaining the steps of how he's done it (link is present in the readme.md file)
