### ISSUE TITLE
I want that new bug should not get created when someone reply on the same Mail

### ISSUE THREAD

**Issue by streamvmady** [Microsoft/mail2bug#85]
Hello,

I'm facing issue while sending reply mail, that is every time i'm replying on the same previous mail it's creating new bug in TFS . so i wanted to ask is there any configuration that we can do so that it stops creating new Bug in TFS when someone reply on the same Mail.

Thanks 
--

**Comment by hershi** [comment]
There definitely is a way - in fact, a big reason for creating Mail2Bug to begin with was to accumulate information from the reply into the original bug.

From what you're describing, I think you have misconfigured your instance. Please go through the setup instructions and make sure that you provided a valid field for storing the conversation ID and confirm that you see conversation IDs are successfully stored in that field by the Mail2Bug.
If converstaion IDs are not stored, then Mail2Bug has no way to know whether this email thread has already been processed and which bug it is tied to.

**Comment by streamvmady** [comment]
Thanks for the reply. But I think i didn't made myself clear in the
previous mail. Actually it's adding new Bug with the same Conversation ID
it's not creating Bug with new Conversation ID on reply.

But i want that it should not add new Bug even with same Conversation ID.
How can i achieve this any help will be welcoming.

Thank you

**Comment by hershi** [comment]
HI @streamvmady , what you are trying to achieve is the way Mail2Bug operates, so this is likely still a configuration issue.
If the conversation ID is properly stored in bugs, then the next likely issue is if the bug query is not properly defined. Mail2Bug uses the query to retrieve all the relevant bugs on startup and create an internal index from conversation ID to bug ID. When a new email is processed, its conversation ID is searched in that internal index and if it's found, the new content is added as a comment to the existing bug rather than creating a new one.
To check this, I'd suggest that you go through the steps for creating the query again, and make sure that the bugs created by Mail2Bug are actually retrieved by it

Cheers,
Guy

**Comment by streamvmady** [comment]
Thankyou man for your help finally got this right this time.

Regards,
