### ISSUE TITLE
Scheduled Task won't run when using VSO

### ISSUE THREAD

**Issue by HintonBR** [Microsoft/mail2bug#9]
I tried to get the Scheduled Task to run using a VSO project but unless I set the Scheduled Task to only run when user is logged in (and have the user logged in) will it auth to VSO.  I suspect it has something to do with OAuth versus Windows Auth - has anyone else been able to get this to work?

**Comment by hershi** [comment]
Hi Hinton,
The tool is currently using ServiceIdentity credentials to authenticate - one thing that may be going wrong is if you're trying to use your standard user credentials instead of these. Can you confirm whether that's the case or not?
There are details in the [fully annotated config](https://github.com/Microsoft/mail2bug/blob/master/Documentation/FullyAnnotatedConfigReference.xml) on how to set these up - copy pasting here for convenience:
- For VS online, you must provision a Service Identity and use it here. This can be done by following the instructions [here] (http://nakedalm.com/getting-service-account-vso-tfs-service-credential-viewer/)
- Note also that for VS online, there will be changes coming soon, since the ServiceIdentity method of authentication is going to be deprecated by VSO in favor of AAD, so if you're using VS online, stay tuned for changes in upcoming versions (ideally, config elements won't change, since username and password would still be needed, but instructions on what values to use might change)

**Comment by hershi** [comment]
OAuth is now supported as well. Please refer to the fully annotated config file for details (search for OAuth)

**Comment by sinapis** [comment]
Hello Hershi,

I'm trying to set up mail2bug against my VSO account but I'm having difficulties understanding what are the proper values for these fields:

        <OAuthContext></OAuthContext> 
        <OAuthResourceId></OAuthResourceId>
        <OAuthClientId></OAuthClientId>

Any chance you can provide more details how to obtain this info for my VSO? Maybe an example?

Thanks,
Amir from Sinapis
